name: stage_ulisse 
services:
  nginx:
    container_name: stage_ulisse_nginx
    build:
      context: ./docker/nginx
      dockerfile: nginx.Dockerfile
    ports: ["80:80"]
    volumes:
      - ./AdvertiseInvaders:/var/www/html 
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      