name: stage_ulisse 
services:
  nginx:
    container_name: stage_ulisse_nginx
    build:
      context: ./docker/nginx
      dockerfile: nginx.Dockerfile
    ports: ["80:80"]
    volumes:
      - ./AdvertiseInvaders:/var/www/html 
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
  bun_backend:
    container_name: stage_ulisse_bun_backend
    image: oven/bun
    # build:
    #   context: ./docker/backend
    #   dockerfile: backend.dockerfile
    ports: ["3000:3000"] 
    volumes: 
      - ./InvadersBackend:/home/bun/app
    entrypoint: []
    #text1
    command: "/bin/sh -c 'bun install && bun run dev'"